### ISSUE TITLE
🚧Implement KDActionUtils library project

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/KDActionUtils#1]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Go through the entire code base and process all of the TODO items. These are related to setting up the code base to be specific for this new project.  Also rename the solution and projects to the required name.

Migrate all of the reusable code that is used across all of the GitHub actions to this library project.

### Acceptance Criteria

**This issue is finished when:**
- [x] Rename solution
- [x] Rename main project
- [x] Rename testing project
- [x] Process all TODO items in the solution
- Bring the following code from [BranchValidator](https://github.com/KinsonDigital/BranchValidator) project
  - [x] AppService
  - [x] ArgParsingService
  - [x] ConsoleService
  - [x] GithubConsoleService
  - [x] IAction
  - [x] ActionOutputService
- ~Create preview release workflow~
  - ~Setup to use GitHub packaging system~
- ~Create production release workflow~
  - ~Setup to use GitHub packaging system~

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [x] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/KDActionUtils/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/KDActionUtils/labels/%F0%9F%A7%A8breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/KDActionUtils/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/KDActionUtils/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/KDActionUtils/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/KDActionUtils/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/KDActionUtils/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/KDActionUtils/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/KDActionUtils/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
