### ISSUE TITLE
🚧Setup release workflows to do GitHub releases

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/KDActionUtils#18]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Setup both the `preview-release.yml` and `production-release.yml` release workflows to perform a GitHub release.   This release will check if the release notes exist, contain a certain title, add the release notes to the release description, and attach the release notes to the release assets.

💡Temporarily change the repo's default branch for testing.

### Acceptance Criteria

- ### **Preview release workflow updated**
   - [x] Checks if the release notes exist
   - [x] Title constructed with the version and to look like 👉🏼 **🚀Preview Release - v1.2.3-preview.4**
   - [x] Checks if release notes exist and if not, fails the workflow
   - [x] Adds the release notes to the description of the release
   - [x] Attaches the release notes to the assets of the release

- ### **Production release workflow updated**
   - [x] Checks if the release notes exist
   - [x] Title constructed with the version and to look like 👉🏼 **🚀Preview Release - v1.2.3**
   - [x] Checks if release notes exist and if not, fails the workflow
   - [x] Adds the release notes to the description of the release
   - [x] Attaches the release notes to the assets of the release

- [x] The repo's default branch changed back to latest preview
- [x] The tag protection rule `v*.*.*-preview.*` has been removed for testing.  Re-add the rule back.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if required)_.
- [x] Issue linked to the correct milestone _(if required)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/KDActionUtils/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/KDActionUtils/labels/%F0%9F%A7%A8breaking%20changes      |
| New Feature         | https://github.com/KinsonDigital/KDActionUtils/labels/%E2%9C%A8new%20feature              |
| Workflow Changes    | https://github.com/KinsonDigital/KDActionUtils/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/KDActionUtils/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/KDActionUtils/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/KDActionUtils/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/KDActionUtils/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/KDActionUtils/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
